/*
 * Copyright (c) 2022-2025 See AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package com.github.tommyettinger.random.experimental;

import com.github.tommyettinger.random.EnhancedRandom;

import java.math.BigInteger;

/**
 * Another attempt at a no-big-magic-numbers generator; very experimental.
 * This is a simplified version of {@link WoolRandom}.
 */
public class YarnRandom extends EnhancedRandom {

	/**
	 * The only state variable; can be any {@code long}.
	 */
	public long state;

	/**
	 * Creates a new YarnRandom with a random state.
	 */
	public YarnRandom() {
		this(EnhancedRandom.seedFromMath());
	}

	/**
	 * Creates a new YarnRandom with the given state; all {@code long} values are permitted.
	 *
	 * @param state any {@code long} value
	 */
	public YarnRandom(long state) {
		super(state);
		this.state = state;
	}

	@Override
	public String getTag() {
		return "WolR";
	}

	/**
	 * Returned by {@link #getMinimumPeriod()}.
	 *
	 * @see #getMinimumPeriod()
	 */
	private static final BigInteger MINIMUM_PERIOD = new BigInteger("10000000000000000", 16);

	/**
	 * 2 to the 64.
	 *
	 * @return 2 to the 64
	 */
	@Override
	public BigInteger getMinimumPeriod() {
		return MINIMUM_PERIOD;
	}

	/**
	 * This has one long state.
	 *
	 * @return 1 (one)
	 */
	@Override
	public int getStateCount() {
		return 1;
	}

	/**
	 * Gets the only state, which can be any long value.
	 *
	 * @param selection ignored; this always returns the same, only state
	 * @return the only state's exact value
	 */
	@Override
	public long getSelectedState(int selection) {
		return state;
	}

	/**
	 * Sets the only state, which can be given any long value. The selection
	 * can be anything and is ignored.
	 *
	 * @param selection ignored; this always sets the same, only state
	 * @param value     the exact value to use for the state; all longs are valid
	 */
	@Override
	public void setSelectedState(int selection, long value) {
		state = value;
	}

	/**
	 * Sets the only state, which can be given any long value; this seed value
	 * will not be altered. Equivalent to {@link #setSelectedState(int, long)}
	 * with any selection and {@code seed} passed as the {@code value}.
	 *
	 * @param seed the exact value to use for the state; all longs are valid
	 */
	@Override
	public void setSeed(long seed) {
		state = seed;
	}

	/**
	 * Gets the current state; it's already public, but I guess this could still
	 * be useful. The state can be any {@code long}.
	 *
	 * @return the current state, as a long
	 */
	public long getState() {
		return state;
	}

	/**
	 * Sets each state variable to the given {@code state}. This implementation
	 * simply sets the one state variable to {@code state}.
	 *
	 * @param state the long value to use for the state variable
	 */
	@Override
	public void setState(long state) {
		this.state = state;
	}

	/**
	 * A GDScript-usable unary hash. GDScript doesn't have unsigned ints or an unsigned right shift.
	 * Despite using only signed right shifts, this is 1D-equidistributed. Given all long values for x,
	 * it will return all long values with equal frequency.
	 *
	 * @param x any 64-bit int
	 * @return any 64-bit int
	 */
	public long mix(long x) {
		x ^= 7L; // Optional, can be used to break up patterns when x is incremented by specific numbers.
		x *= 5555555555555555555L; // Nineteen 5's; could also be 3's or 7's, or almost any big odd number, really.
		x += x * x | 123456789L; // The 123456789L constant can be any number of comparable size, ORed with 5L.
		x ^= x >> 29 ^ x >> 63; // Signed right shifts because that's all GDScript has.
		x += x * x | 123456789L; // This can use the same or a different constant as above.
		x ^= x >> 27 ^ x >> 63; // One different shift; this matters for unclear reasons.
		return x;
	}

	@Override
	public long nextLong() {
		return mix(++state);
	}

	/**
	 * Skips the state forward or backwards by the given {@code advance}, then returns the result of {@link #nextLong()}
	 * at the same point in the sequence. If advance is 1, this is equivalent to nextLong(). If advance is 0, this
	 * returns the same {@code long} as the previous call to the generator (if it called nextLong()), and doesn't change
	 * the state. If advance is -1, this moves the state backwards and produces the {@code long} before the last one
	 * generated by nextLong(). More positive numbers move the state further ahead, and more negative numbers move the
	 * state further behind; all of these take constant time.
	 *
	 * @param advance how many steps to advance the state before generating a {@code long}
	 * @return a random {@code long} by the same algorithm as {@link #nextLong()}, using the appropriately-advanced state
	 */
	@Override
	public long skip(long advance) {
		return mix(state += advance);
	}

	@Override
	public long previousLong() {
		return mix(state--);
	}

	@Override
	public int next(int bits) {
		return (int) (mix(++state)) >>> (32 - bits);
	}

	@Override
	public YarnRandom copy() {
		return new YarnRandom(state);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o)
			return true;
		if (o == null || getClass() != o.getClass())
			return false;

		YarnRandom that = (YarnRandom) o;

		return state == that.state;
	}

	@Override
	public String toString() {
		return "YarnRandom{state=" + (state) + "L}";
	}
}
